---
- hosts: localhost

  tasks:
  - name: create docker image using war file
    command: docker build -t tomcat-web:latest .
    args:
      chdir: /opt/k8s

  - name: create tag to image
    command: docker tag tomcat-web vhirewadeyar/tomcat-web

  - name: push image on to dockerhub
    command: docker push vhirewadeyar/tomcat-web

  - name: remove docker images form ansible server
    command: docker rmi  tomcat-web:latest vhirewadeyar/tomcat-web
    ignore_errors: yes

